force-app/main/default/objects/Conditions_Generales__c/Conditions_Generales__c.object-meta.xml
<CustomObject>
    <label>Conditions Générales</label>
    <nameField>
        <label>General Condition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conditions Générales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Conditions_Generales__c/fields/English_version__c.field-meta.xml
<CustomField>
    <fullName>English_version__c</fullName>
    <label>English version</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Conditions_Generales__c/fields/French_version__c.field-meta.xml
<CustomField>
    <fullName>French_version__c</fullName>
    <label>French version</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Cotation__c/Cotation__c.object-meta.xml
<CustomObject>
    <label>Cotation</label>
    <nameField>
        <label>Cotation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cotations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cotation__c/fields/Langue_des_conditions_generales__c.field-meta.xml
<CustomField>
    <fullName>Langue_des_conditions_generales__c</fullName>
    <label>Langue des conditions générales</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>EN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cotation__c/fields/Opportunite__c.field-meta.xml
<CustomField>
    <fullName>Opportunite__c</fullName>
    <label>Opportunité</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cotations</relationshipLabel>
    <relationshipName>Cotations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cotation__c/fields/Type_de_service__c.field-meta.xml
<CustomField>
    <fullName>Type_de_service__c</fullName>
    <label>Type de service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fret Maritime</fullName>
            </value>
            <value>
                <fullName>Fret Aérien</fullName>
            </value>
            <value>
                <fullName>Fret Routier</fullName>
            </value>
            <value>
                <fullName>Transit</fullName>
            </value>
            <value>
                <fullName>Logistique</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Type_de_service__c.field-meta.xml
<CustomField>
    <fullName>Type_de_service__c</fullName>
    <label>Type de service</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fret Maritime</fullName>
            </value>
            <value>
                <fullName>Fret Aérien</fullName>
            </value>
            <value>
                <fullName>Fret Routier</fullName>
            </value>
            <value>
                <fullName>Transit</fullName>
            </value>
            <value>
                <fullName>Logistique</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Bypass_Flow__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Flow__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Flow</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Bypass_VR__c.field-meta.xml
<CustomField>
    <fullName>Bypass_VR__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass VR</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/VF_Cotation_2_Controller_Test.cls
@isTest
public class VF_Cotation_2_Controller_Test {
    @TestSetup
    static void makeData(){
        System.runAs(getDfaultAdminUser()){
            Account acc = new Account();
            acc.Name = 'Test Account';
            // Create a dummy Opportunity record if required by Cotation__c
            Opportunity opp = new Opportunity(
                Name = 'Test Opp',
                StageName = 'Analyse',
                CloseDate = Date.today(),
                AccountId = acc.Id
            );
            insert opp;
            
            // Create a dummy Cotation__c record with required fields
            Cotation__c cotation = new Cotation__c(
                Name = 'Test Cotation',
                Opportunite__c = opp.Id,
                Type_de_service__c = 'Fret Aérien',
                Langue_des_conditions_generales__c = 'EN'
            );
            insert cotation;

            Conditions_Generales__c conditions = new Conditions_Generales__c(
                Name = 'CONDITIONS GENERALES DE PRESTATIONS DE SERVICES',
                English_version__c = 'Test English',
                French_version__c = 'Test French'
            );
            insert conditions;
        }
    }

    @isTest
    static void testController(){
        System.runAs(getDfaultAdminUser()){
    
            // Create a dummy Cotation__c record with required fields
            Cotation__c cotation = [SELECT Id from Cotation__c LIMIT 1];
            // Set up page parameters: supply the 'id' parameter to simulate a Visualforce request
            PageReference pageRef = Page.VF_Cotation; // Use any existing VF page (DummyPage used solely for parameter passing)
            pageRef.getParameters().put('id', String.valueOf(cotation.Id));
            pageRef.getParameters().put('cotationLanguage', 'EN');
            Test.setCurrentPage(pageRef);
            
            // Create the standard controller and instance of PDFController
            ApexPages.StandardController sc = new ApexPages.StandardController(cotation);
            new VF_Cotation_2_Controller(sc);
        }
    }

    private static User getDfaultAdminUser(){
        
        User us = [SELECT Bypass_Flow__c , Bypass_VR__c FROM User WHERE Profile.Name = 'System Administrator' AND isActive = true LIMIT 1];

        us.Bypass_Flow__c = true;
        us.Bypass_VR__c = true;
        update us;

        return us;
    }
}