force-app/main/default/objects/Article__c/Article__c.object-meta.xml
<CustomObject>
    <label>Article</label>
    <nameField>
        <label>Designation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Conditions_Generales__c/Conditions_Generales__c.object-meta.xml
<CustomObject>
    <label>Conditions Générales</label>
    <nameField>
        <label>General Condition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conditions Générales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Conditions_Generales__c/fields/English_version__c.field-meta.xml
<CustomField>
    <fullName>English_version__c</fullName>
    <label>English version</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Conditions_Generales__c/fields/French_version__c.field-meta.xml
<CustomField>
    <fullName>French_version__c</fullName>
    <label>French version</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Cotation__c/Cotation__c.object-meta.xml
<CustomObject>
    <label>Cotation</label>
    <nameField>
        <label>Cotation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cotations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ligne_de_cotation__c/Ligne_de_cotation__c.object-meta.xml
<CustomObject>
    <label>Ligne de cotation</label>
    <nameField>
        <displayFormat>Article{0000}</displayFormat>
        <label>Ligne de cotation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lignes de cotation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ligne_de_cotation__c/fields/Article__c.field-meta.xml
<CustomField>
    <fullName>Article__c</fullName>
    <label>Article</label>
    <referenceTo>Article__c</referenceTo>
    <relationshipLabel>Lignes de cotation</relationshipLabel>
    <relationshipName>Lignes_de_cotation</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ligne_de_cotation__c/fields/Cotation__c.field-meta.xml
<CustomField>
    <fullName>Cotation__c</fullName>
    <label>Cotation</label>
    <referenceTo>Cotation__c</referenceTo>
    <relationshipLabel>Lignes de cotation</relationshipLabel>
    <relationshipName>Lignes_de_cotation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ligne_de_cotation__c/fields/Prix__c.field-meta.xml
<CustomField>
    <fullName>Prix__c</fullName>
    <label>Prix</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Ligne_de_cotation__c/fields/Prix_Total_TTC__c.field-meta.xml
<CustomField>
    <fullName>Prix_Total_TTC__c</fullName>
    <formula>(Prix__c * Quantite__c) * (1 + (Article__r.TVA__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Prix Total TTC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/VF_Cotation_2_Controller.cls
public class VF_Cotation_2_Controller {
    
    public List<Ligne_de_cotation__c> quotationLines{ get; set; }
    public String cotationLanguage{ get; set; }
    public Conditions_Generales__c conditions { get; set; }
    
    public VF_Cotation_2_Controller(ApexPages.StandardController controller) {
        
        String quotationId = ApexPages.currentPage().getParameters().get('Id');
        cotationLanguage = ApexPages.currentPage().getParameters().get('cotationLanguage');
        
        quotationLines = [SELECT Article__r.Name , Prix__c , Prix_Total_TTC__c , Commentaire__c , CurrencyIsoCode FROM Ligne_de_cotation__c WHERE Cotation__c = :quotationId];
        conditions = [SELECT English_version__c , French_version__c FROM Conditions_Generales__c WHERE Name = 'CONDITIONS GENERALES DE PRESTATIONS DE SERVICES' LIMIT 1];
    }
    
}