force-app/main/default/objects/Article__c/Article__c.object-meta.xml
<CustomObject>
    <label>Article</label>
    <nameField>
        <label>Designation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Article__c/fields/Entite_Juridique__c.field-meta.xml
<CustomField>
    <fullName>Entite_Juridique__c</fullName>
    <label>Entité Juridique</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TST</fullName>
            </value>
            <value>
                <fullName>TRO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Article__c/fields/TVA__c.field-meta.xml
<CustomField>
    <fullName>TVA__c</fullName>
    <label>TVA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Conditions_Generales__c/Conditions_Generales__c.object-meta.xml
<CustomObject>
    <label>Conditions Générales</label>
    <nameField>
        <label>General Condition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conditions Générales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Conditions_Generales__c/fields/English_version__c.field-meta.xml
<CustomField>
    <fullName>English_version__c</fullName>
    <label>English version</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Conditions_Generales__c/fields/French_version__c.field-meta.xml
<CustomField>
    <fullName>French_version__c</fullName>
    <label>French version</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Cotation__c/Cotation__c.object-meta.xml
<CustomObject>
    <label>Cotation</label>
    <nameField>
        <label>Cotation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cotations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cotation__c/fields/Langue_des_conditions_generales__c.field-meta.xml
<CustomField>
    <fullName>Langue_des_conditions_generales__c</fullName>
    <label>Langue des conditions générales</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>EN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cotation__c/fields/Opportunite__c.field-meta.xml
<CustomField>
    <fullName>Opportunite__c</fullName>
    <label>Opportunité</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cotations</relationshipLabel>
    <relationshipName>Cotations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cotation__c/fields/Type_de_service__c.field-meta.xml
<CustomField>
    <fullName>Type_de_service__c</fullName>
    <label>Type de service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fret Maritime</fullName>
            </value>
            <value>
                <fullName>Fret Aérien</fullName>
            </value>
            <value>
                <fullName>Fret Routier</fullName>
            </value>
            <value>
                <fullName>Transit</fullName>
            </value>
            <value>
                <fullName>Logistique</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ligne_de_cotation__c/Ligne_de_cotation__c.object-meta.xml
<CustomObject>
    <label>Ligne de cotation</label>
    <nameField>
        <displayFormat>Article{0000}</displayFormat>
        <label>Ligne de cotation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lignes de cotation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ligne_de_cotation__c/fields/Article__c.field-meta.xml
<CustomField>
    <fullName>Article__c</fullName>
    <label>Article</label>
    <referenceTo>Article__c</referenceTo>
    <relationshipLabel>Lignes de cotation</relationshipLabel>
    <relationshipName>Lignes_de_cotation</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ligne_de_cotation__c/fields/Cotation__c.field-meta.xml
<CustomField>
    <fullName>Cotation__c</fullName>
    <label>Cotation</label>
    <referenceTo>Cotation__c</referenceTo>
    <relationshipLabel>Lignes de cotation</relationshipLabel>
    <relationshipName>Lignes_de_cotation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ligne_de_cotation__c/fields/Prix__c.field-meta.xml
<CustomField>
    <fullName>Prix__c</fullName>
    <label>Prix</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Ligne_de_cotation__c/fields/Prix_Total_HT__c.field-meta.xml
<CustomField>
    <fullName>Prix_Total_HT__c</fullName>
    <formula>Prix__c *  Quantite__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Prix Total HT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Ligne_de_cotation__c/fields/Prix_Total_TTC__c.field-meta.xml
<CustomField>
    <fullName>Prix_Total_TTC__c</fullName>
    <formula>(Prix__c * Quantite__c) * (1 + (Article__r.TVA__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Prix Total TTC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Entite_Juridique__c.field-meta.xml
<CustomField>
    <fullName>Entite_Juridique__c</fullName>
    <label>Entité Juridique</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TST</fullName>
            </value>
            <value>
                <fullName>TRO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Type_de_service__c.field-meta.xml
<CustomField>
    <fullName>Type_de_service__c</fullName>
    <label>Type de service</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fret Maritime</fullName>
            </value>
            <value>
                <fullName>Fret Aérien</fullName>
            </value>
            <value>
                <fullName>Fret Routier</fullName>
            </value>
            <value>
                <fullName>Transit</fullName>
            </value>
            <value>
                <fullName>Logistique</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Support__c/Support__c.object-meta.xml
<CustomObject>
    <label>Support</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Support Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Support__c/fields/Chargeable_Value__c.field-meta.xml
<CustomField>
    <fullName>Chargeable_Value__c</fullName>
    <formula>IF(
  AND(
    ISPICKVAL(Cotation__r.Type_de_service__c, &quot;Fret Maritime&quot;),
    ISPICKVAL(Cotation__r.Type_d_exp_dition__c, &quot;Groupage&quot;)
  ),
  ( Longueur__c * Largeur__c * Hauteur__c ) / 1000000,
  IF(
    OR(
       AND(
      ISPICKVAL(Cotation__r.Type_de_service__c, &quot;Fret Routier&quot;),
      ISPICKVAL(Cotation__r.Type_d_exp_dition__c, &quot;Groupage gerbable&quot;)
      ),
ISPICKVAL(Cotation__r.Type_de_service__c, &quot;Fret Aérien&quot;)),
    Longueur__c * Largeur__c * Hauteur__c * Cotation__r.TECH_Cnsnt_de_calcul_Chargeable_value__c / 1000000,
    0
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Chargeable Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Support__c/fields/Cotation__c.field-meta.xml
<CustomField>
    <fullName>Cotation__c</fullName>
    <label>Cotation</label>
    <referenceTo>Cotation__c</referenceTo>
    <relationshipLabel>Supports</relationshipLabel>
    <relationshipName>Supports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/VF_Cotation_Controller.cls
public with sharing class VF_Cotation_Controller {
    public String recordId{ get; set; }
    public String cotationLanguage { get; set; }
    public List<Ligne_de_cotation__c> quotationLines{ get; set; }
    public Decimal chargeableTotalValue{ get; set; }
    public Conditions_Generales__c conditions { get; set; }


    // Constructor to retrieve recordId from page parameters
    public VF_Cotation_Controller(ApexPages.StandardController controller) {
        recordId = ApexPages.currentPage().getParameters().get('id');
        Cotation__c cotation = [SELECT Name, Type_de_service__c ,Opportunite__r.Entite_Juridique__c, Langue_des_conditions_generales__c FROM Cotation__c WHERE Id = :recordId];
        
        cotationLanguage = cotation.Langue_des_conditions_generales__c ;
        quotationLines = [SELECT Article__r.Name ,Article__r.TVA__c,  Prix__c ,Prix_Total_HT__c, Prix_Total_TTC__c, Commentaire__c , CurrencyIsoCode FROM Ligne_de_cotation__c WHERE Cotation__c = :recordId];
        conditions = [SELECT English_version__c , French_version__c FROM Conditions_Generales__c WHERE Name = 'CONDITIONS GENERALES DE PRESTATIONS DE SERVICES' LIMIT 1];

        calculateChargeableValue();
    }

    public void calculateChargeableValue(){
       chargeableTotalValue = 0;
        for(Support__c support : [SELECT Chargeable_Value__c FROM Support__c WHERE Cotation__c = :recordId]){
            chargeableTotalValue += support.Chargeable_Value__c;
        }
    }
}