force-app/main/default/objects/Account/fields/Client_confrere__c.field-meta.xml
<CustomField>
    <fullName>Client_confrere__c</fullName>
    <label>Client confrère</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
                <default>true</default>
                <label>Non</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Entite_Juridique__c.field-meta.xml
<CustomField>
    <fullName>Entite_Juridique__c</fullName>
    <formula>TEXT(Owner.Entite_Juridique__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entité Juridique</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Trafic__c.field-meta.xml
<CustomField>
    <fullName>Trafic__c</fullName>
    <label>Trafic</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Transit</fullName>
            </value>
            <value>
                <fullName>Import</fullName>
            </value>
            <value>
                <fullName>Export</fullName>
            </value>
            <value>
                <fullName>Logistique</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Article__c/Article__c.object-meta.xml
<CustomObject>
    <label>Article</label>
    <nameField>
        <label>Designation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Article__c/fields/Entite_Juridique__c.field-meta.xml
<CustomField>
    <fullName>Entite_Juridique__c</fullName>
    <label>Entité Juridique</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TST</fullName>
            </value>
            <value>
                <fullName>TRO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Fonction__c.field-meta.xml
<CustomField>
    <fullName>Fonction__c</fullName>
    <label>Fonction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Directeur</fullName>
            </value>
            <value>
                <fullName>Responsable</fullName>
            </value>
            <value>
                <fullName>Agent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direction</fullName>
            </value>
            <value>
                <fullName>Achat</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Logistique</fullName>
            </value>
            <value>
                <fullName>Qualité</fullName>
            </value>
            <value>
                <fullName>Opération</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cotation__c/Cotation__c.object-meta.xml
<CustomObject>
    <label>Cotation</label>
    <nameField>
        <label>Cotation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cotations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cotation__c/fields/Date_de_debut__c.field-meta.xml
<CustomField>
    <fullName>Date_de_debut__c</fullName>
    <label>Date de début</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cotation__c/fields/Marchandises__c.field-meta.xml
<CustomField>
    <fullName>Marchandises__c</fullName>
    <label>Marchandises</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General Cargo</fullName>
            </value>
            <value>
                <fullName>DGR Goods</fullName>
            </value>
            <value>
                <fullName>Périssable</fullName>
            </value>
            <value>
                <fullName>Pharma</fullName>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cotation__c/fields/Niveau_de_service__c.field-meta.xml
<CustomField>
    <fullName>Niveau_de_service__c</fullName>
    <label>Niveau de service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>AOG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cotation__c/fields/Opportunite__c.field-meta.xml
<CustomField>
    <fullName>Opportunite__c</fullName>
    <label>Opportunité</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cotations</relationshipLabel>
    <relationshipName>Cotations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cotation__c/fields/Type_de_colis__c.field-meta.xml
<CustomField>
    <fullName>Type_de_colis__c</fullName>
    <label>Type de colis</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Palette</fullName>
            </value>
            <value>
                <fullName>Conteneur</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cotation__c/fields/Type_de_service__c.field-meta.xml
<CustomField>
    <fullName>Type_de_service__c</fullName>
    <label>Type de service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fret Maritime</fullName>
            </value>
            <value>
                <fullName>Fret Aérien</fullName>
            </value>
            <value>
                <fullName>Fret Routier</fullName>
            </value>
            <value>
                <fullName>Transit</fullName>
            </value>
            <value>
                <fullName>Logistique</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ligne_de_cotation__c/Ligne_de_cotation__c.object-meta.xml
<CustomObject>
    <label>Ligne de cotation</label>
    <nameField>
        <displayFormat>Article{0000}</displayFormat>
        <label>Ligne de cotation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lignes de cotation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ligne_de_cotation__c/fields/Article__c.field-meta.xml
<CustomField>
    <fullName>Article__c</fullName>
    <label>Article</label>
    <referenceTo>Article__c</referenceTo>
    <relationshipLabel>Lignes de cotation</relationshipLabel>
    <relationshipName>Lignes_de_cotation</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ligne_de_cotation__c/fields/Cotation__c.field-meta.xml
<CustomField>
    <fullName>Cotation__c</fullName>
    <label>Cotation</label>
    <referenceTo>Cotation__c</referenceTo>
    <relationshipLabel>Lignes de cotation</relationshipLabel>
    <relationshipName>Lignes_de_cotation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ligne_de_cotation__c/fields/Prix__c.field-meta.xml
<CustomField>
    <fullName>Prix__c</fullName>
    <label>Prix</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Ligne_de_cotation__c/fields/Quantite__c.field-meta.xml
<CustomField>
    <fullName>Quantite__c</fullName>
    <label>Quantité</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Date_de_concretisation__c.field-meta.xml
<CustomField>
    <fullName>Date_de_concretisation__c</fullName>
    <label>Date de concrétisation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Date_de_debut__c.field-meta.xml
<CustomField>
    <fullName>Date_de_debut__c</fullName>
    <label>Date de début</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Entite_Juridique__c.field-meta.xml
<CustomField>
    <fullName>Entite_Juridique__c</fullName>
    <label>Entité Juridique</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TST</fullName>
            </value>
            <value>
                <fullName>TRO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Nombre_de_colis__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_colis__c</fullName>
    <label>Nombre de colis</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Nombre_de_dossier_transit__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_dossier_transit__c</fullName>
    <label>Nombre de dossier transit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Type_de_colis__c.field-meta.xml
<CustomField>
    <fullName>Type_de_colis__c</fullName>
    <label>Type de colis</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Palette</fullName>
            </value>
            <value>
                <fullName>Conteneur</fullName>
            </value>
            <value>
                <fullName>Colis</fullName>
            </value>
            <value>
                <fullName>Remorque</fullName>
            </value>
            <value>
                <fullName>Kg</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Type_de_service__c.field-meta.xml
<CustomField>
    <fullName>Type_de_service__c</fullName>
    <label>Type de service</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fret Maritime</fullName>
            </value>
            <value>
                <fullName>Fret Aérien</fullName>
            </value>
            <value>
                <fullName>Fret Routier</fullName>
            </value>
            <value>
                <fullName>Transit</fullName>
            </value>
            <value>
                <fullName>Logistique</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Type_de_vente__c.field-meta.xml
<CustomField>
    <fullName>Type_de_vente__c</fullName>
    <label>Type de vente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consultation</fullName>
            </value>
            <value>
                <fullName>AO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LigneDeCotationControllerTest.cls
@isTest
public with sharing class LigneDeCotationControllerTest {

    @TestSetup
    static void setupTestData() {
    /*
        Account acc = new Account(Name = 'Test Account', Industry= 'High-tech', Type = 'Compte', BillingPostalCode = '20450', BillingCity = 'Casablanca', Client_confrere__c = 'Non', AccountSource ='Partner', Trafic__c = 'Transit', Phone = '00212675836252');
        insert acc;
        Contact con = new Contact(Title = 'title', FirstName = 'Test', LastName = 'Contact', Email = 'Example@email.com', Phone = '00212675836252', AccountId = acc.Id,  Fonction__c ='Directeur', Service__c = 'Direction', Department = 'something');
        insert con;
        Date currentDate = Date.today();
        Opportunity Opp = new Opportunity(Name = 'Test Opportunity',StageName = 'Qualification', Nombre_de_dossier_transit__c = 18, AccountId = acc.Id, Type_de_vente__c = 'Consultation', Type_de_service__c = 'Transit', Entite_Juridique__c = 'TST', Nombre_de_colis__c = 12, Volume_prevu__c = 134, Type_de_colis__c = 'Conteneur', Date_de_debut__c = currentDate, Date_de_concretisation__c = currentDate.addDays(6), CloseDate = currentDate.addDays(10));
        insert Opp;
        
        // Create test Article__c records
        List<Article__c> articlesList = new List<Article__c>();
        articlesList.add(new Article__c(Name = 'Article 1', Entite_Juridique__c = 'TST'));
        articlesList.add(new Article__c(Name = 'Article 2', Entite_Juridique__c = 'TST'));
        articlesList.add(new Article__c(Name = 'Article 3', Entite_Juridique__c = 'TST'));
        articlesList.add(new Article__c(Name = 'Article 4', Entite_Juridique__c = 'TST'));
        insert articlesList;

        // Create a test Cotation__c record
        Cotation__c cotation = new Cotation__c(Name = 'Test Cotation', Opportunite__c = opp.Id, Hauteur__c = 15, Longueur__c = 15, Largeur__c = 15, Niveau_de_service__c = 'AOG', Type_de_service__c= 'Fret Maritime', Marchandises__c = 'DGR Goods');
        insert cotation;

        // Create test Ligne_de_cotation__c records
        List<Ligne_de_cotation__c> cotationLignes = new List<Ligne_de_cotation__c>();
        cotationLignes.add(new Ligne_de_cotation__c(Article__c = articlesList[0].Id, Cotation__c = cotation.Id, Prix__c = 300000, Quantite__c = 1));
        cotationLignes.add(new Ligne_de_cotation__c(Article__c = articlesList[1].Id, Cotation__c = cotation.Id, Prix__c = 800000, Quantite__c = 10));
        insert cotationLignes;
        */
    }

    @isTest
    static void testGetLignes() {
    /*
        // Call the method to be tested
        List<Article__c> result = LigneDeCotationController.getLignes();

        // Verify the results
        System.assertNotEquals(0, result.size(), 'Expected some articles to be returned');
        for (Article__c article : result) {
            System.assertEquals('TST', article.Entite_Juridique__c, 'Entite_Juridique__c should be TST');
        }
        */
    }

    @isTest
    static void testSaveLignes() {
    /*
        // Query the test articles
        List<Article__c> articlesList = [SELECT Id FROM Article__c ORDER BY Name LIMIT 2];
        System.assert(articlesList.size() >= 2, 'Expected at least 2 articles for association');

        // Query the test cotation
        Cotation__c cotation = [SELECT Id FROM Cotation__c LIMIT 1];

        // Create test Ligne_de_cotation__c records
        List<Ligne_de_cotation__c> lignes = new List<Ligne_de_cotation__c>();
        lignes.add(new Ligne_de_cotation__c(Article__c = articlesList[0].Id, Cotation__c = cotation.Id, Prix__c = 300000, Quantite__c = 1));
        lignes.add(new Ligne_de_cotation__c(Article__c = articlesList[1].Id, Cotation__c = cotation.Id, Prix__c = 800000, Quantite__c = 10));

        // Call the method to be tested
        Test.startTest();
        LigneDeCotationController.saveLignes(lignes);
        Test.stopTest();

        // Verify the results
        List<Ligne_de_cotation__c> savedLignes = [SELECT Id, Name, Cotation__c FROM Ligne_de_cotation__c WHERE Id =: lignes];
        System.assertEquals(2, savedLignes.size(), 'Expected 2 Ligne_de_cotation__c records to be inserted');
    */
    }
    

    @isTest
    static void testSaveLignesWithException() {
    /*
        // Create a test Ligne_de_cotation__c record with invalid data to force an exception
        List<Ligne_de_cotation__c> lignes = new List<Ligne_de_cotation__c>();
        lignes.add(new Ligne_de_cotation__c());

        // Call the method to be tested and expect an exception
        Test.startTest();
        try {
            LigneDeCotationController.saveLignes(lignes);
            System.assert(false, 'Expected an exception to be thrown');
        } catch (AuraHandledException e) {
            system.debug('error message ==> '+ e.getMessage());
            // Confirm the expected exception message is contained in the exception thrown
            System.assert(e.getMessage().contains('Insert failed'), 'Expected error message to contain "Error saving records"');
        }
        Test.stopTest();
        */
    }
}